<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BmiRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simei", models.CharField(max_length=50, verbose_name="お名前")),
                ("height", models.FloatField(verbose_name="身長(cm)")),
                ("weight", models.FloatField(verbose_name="体重(kg)")),
            ],
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BmiRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simei", models.CharField(max_length=50, verbose_name="お名前")),
                ("height", models.FloatField(verbose_name="身長(cm)")),
                ("weight", models.FloatField(verbose_name="体重(kg)")),
            ],
        ),
    ]
>>>>>>> 02eda6b (2025_1115_mypage_custom)
